### ISSUE TITLE
Additional social icons

### ISSUE THREAD

**Issue by BoltzmannBrain** [francescoes/jsonresume-theme-stackoverflow#35]
How can we add social icons for [google scholar](https://scholar.google.com/) and arxiv ([here](https://jpswalsh.github.io/academicons/))? Specifically, how can one generate the svg path code in share.html? Thanks!

**Comment by francescoes** [comment]
currently it's used font awesome for social icons, so there no support of any other icons.
In order to implement it properly we would need to have a more modern stack (e.g. webpack, rollup) or create handlebar helper to support svg icons, we need to investigate in that way.
If we find good, open source, svg icons I am open to migrate from font-awesome to svg
